import type { Metadata } from "next";
import { Questrial as FontSans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import { cn } from "@/lib/utils";
import { Header } from "@/components/Header/Header";
import  Sidebar  from "@/components/Sidebar/Sidebar";

const fontSans = FontSans({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Colaborar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning className="antialiased">
      <body
        className={cn(
          "flex min-h-screen font-sans antialiased bg-background text-foreground ml-14",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar />
          <main className="w-full min-h-screen">
            <Header />
            <div className="p-6">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
